# Generated by Django 4.0.3 on 2022-04-04 17:03

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Forum',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254)),
                ('topic', models.CharField(max_length=300)),
                ('description', models.TextField(max_length=500)),
                ('link', models.CharField(max_length=100)),
                ('status', models.IntegerField(choices=[(0, 'Waiting'), (1, 'Approved')], default=0)),
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='forum_topics', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-date_created'],
            },
        ),
        migrations.CreateModel(
            name='Discussion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('discussion_body', models.TextField(max_length=1000)),
                ('forum', models.ForeignKey(default='Economy today', on_delete=django.db.models.deletion.CASCADE, related_name='discussion_threads', to='qforum.forum')),
            ],
        ),
    ]
