# Generated by Django 4.0.3 on 2022-04-18 06:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('qforum', '0002_category_post_thread_vote_remove_forum_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='thread',
            name='slug',
            field=models.SlugField(max_length=300, null=True),
        ),
    ]
