# Generated by Django 4.0.3 on 2022-04-21 07:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('qforum', '0008_rename_content_reply_message_remove_reply_approved_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='thread',
            name='comments',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='qforum.comment'),
        ),
    ]
