# Generated by Django 4.0.3 on 2022-05-01 12:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('qforum', '0015_alter_comment_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='name',
            field=models.EmailField(max_length=254, null=True),
        ),
    ]
