# Generated by Django 4.0.3 on 2022-05-05 10:35

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('qforum', '0017_remove_comment_body_remove_comment_email_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='likes',
            field=models.ManyToManyField(blank=True, related_name='forum_likes', to=settings.AUTH_USER_MODEL),
        ),
    ]
