# Generated by Django 4.0.3 on 2022-05-11 17:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('qforum', '0018_comment_likes'),
    ]

    operations = [
        migrations.AddField(
            model_name='thread',
            name='thread_views',
            field=models.IntegerField(default=0),
        ),
    ]
