# Generated by Django 4.0.3 on 2022-05-29 21:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('qforum', '0020_comment_dislikes_thread_down_votes_thread_up_votes_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='subject',
            field=models.CharField(default='Uncategorized', max_length=50),
        ),
    ]
