# Generated by Django 4.0.3 on 2022-06-01 13:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('qforum', '0021_alter_category_subject'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='thread',
            name='thread_views',
        ),
    ]
