# Generated by Django 4.0.3 on 2022-07-02 14:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('qforum', '0022_remove_thread_thread_views'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='comment',
            options={'ordering': ['-created']},
        ),
    ]
