# Generated by Django 4.0.3 on 2022-07-19 12:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('qforum', '0023_alter_comment_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='content',
            field=models.TextField(max_length=900, null=True),
        ),
    ]
